name: spatchy-net-2026
services:
  spatchy.net:
    image: spatchy.net
    container_name: spatchy-net-2026
    ports:
      - 8000:8000
    volumes:
      - ./feed-data:/app/feed-data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FRESH_PUBLIC_RSS_FEED_URL=https://spatchy.net/api/feed